blank_issues_enabled: true
contact_links:
  - name: Report a security vulnerability
    url: ../../SECURITY.md
    about: Please review our security policy on how to report security vulnerabilities responsibly.
